### PR TITLE
T540p enhancements

### PR DESCRIPTION
**Pull request by lemenkov**

### CODE REVIEW

**Comment by Jikstra** [comment]
First off, thanks a lot for your efforts :) 
I don't know how much sense it makes to maintain it on this fork instead of doing it on the official coreboot git. 
Besides this, @xfbs currently has my flashable T540p so i can't really test this out. He's working with a friend on porting coreboot to that laptop too, maybe you people can get in contact and exchange work/knowledge?

**Comment by xfbs** [comment]
@felixsinger and I will maybe test this tonight and see if we can get something working

**Comment by lemenkov** [comment]
Hello @xfbs @Jikstra !
I've made this PR here just because there is no way to do it in Gerrit. Please test these patches above and melt/squash it into CB:38204.

**Comment by archfan** [comment]
> @felixsinger and I will maybe test this tonight and see if we can get something working

Can you post your debug logs? I would like to see where it fails.

**Comment by lemenkov** [comment]
@xfbs any news? :)

**Pull request closed without merging**
